/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


typedef NSString * MCMCUserIdentifier;

@interface MCMCTextMessage : NSObject <TBase, NSCoding> {
  MCMCUserIdentifier __originator;
  NSString * __text;

  BOOL __originator_isset;
  BOOL __text_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=originator, setter=setOriginator:) MCMCUserIdentifier originator;
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
#endif

- (id) init;
- (id) initWithOriginator: (MCMCUserIdentifier) originator text: (NSString *) text;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (MCMCUserIdentifier) originator;
- (void) setOriginator: (MCMCUserIdentifier) originator;
#endif
- (BOOL) originatorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

@end

@interface MCMCBroadcast : NSObject <TBase, NSCoding> {
  MCMCTextMessage * __textMessage;

  BOOL __textMessage_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=textMessage, setter=setTextMessage:) MCMCTextMessage * textMessage;
#endif

- (id) init;
- (id) initWithTextMessage: (MCMCTextMessage *) textMessage;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (MCMCTextMessage *) textMessage;
- (void) setTextMessage: (MCMCTextMessage *) textMessage;
#endif
- (BOOL) textMessageIsSet;

@end

@interface MCMCDataFrame : NSObject <TBase, NSCoding> {
  MCMCBroadcast * __broadcast;

  BOOL __broadcast_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=broadcast, setter=setBroadcast:) MCMCBroadcast * broadcast;
#endif

- (id) init;
- (id) initWithBroadcast: (MCMCBroadcast *) broadcast;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (MCMCBroadcast *) broadcast;
- (void) setBroadcast: (MCMCBroadcast *) broadcast;
#endif
- (BOOL) broadcastIsSet;

@end

@interface MCMCprotocolConstants : NSObject {
}
@end
